# Generated by Django 2.0.2 on 2020-11-12 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20201111_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='jobs',
        ),
    ]
